### ISSUE TITLE
在ensemble预测框架中，通过输入特征矩阵（例如[30，3]）来预测未来的一天数值，这里使用的输入是经过分解得到的分量，那么未来的数据是未知的，这个输入怎么来的呢，请问这个该怎么理解

### ISSUE THREAD

**Issue by yangyouxi123456** [FateMurphy/CEEMDAN_LSTM#26]

**Comment by FateMurphy** [comment]
可以理解为ensemble是分解后，用之前一段时间全部分解的结果（imf0-x）作为特征预测今日数据。respective则是分解的每条序列单独预测。

**Comment by yangyouxi123456** [comment]
收到！

**Comment by yangyouxi123456** [comment]
如果使用ensemble预测未知数据，使用的输入是未知的数据进行分解得到的co-imf，这个是不对的，因为未知的数据就没法对其进行分解，我理解Ensemble只能预测一个点，不能预测一段序列

**Comment by FateMurphy** [comment]
目前你直接使用ensemble预测的最终结果可以看作是多个点的集合，而不是一段连续的未来序列。

**Comment by yangyouxi123456** [comment]
知道了，感谢您的回答
