### ISSUE TITLE
关于Hybrid_LSTM函数enlarge参数的疑问

### ISSUE THREAD

**Issue by Whimmey** [FateMurphy/CEEMDAN_LSTM#4]
作者你好，最近拜读了您的论文，并也已经通过repo的代码复现出来了，但在理解上有些问题。

在源码中，代表最终Hybrid模型的Hybrid_LSTM函数，enlarge参数的功能我没太理解。
https://github.com/FateMurphy/CEEMDAN_LSTM/blob/5b40c6aecb90f4460dbbc14015912d108af758a9/CEEMDAN_LSTM.py#L1227
此处，enlarge被用来放大EPOCHS和PATIENCE这两个LSTM模型的超参数，在完成Co-IMF0的Ensemble LSTM预测后，EPOCHS和PATIENCE的值又恢复到原值。

请问这放大操作对Ensemble LSTM的意义是什么呢？enlarge的大小是如何设置的呢，是依据Co-IMF0再次分解所用VMD的K值来取吗？

**Comment by FateMurphy** [comment]
感谢你的提问，enlarge并没有特殊含义。只是为了方便增大epochs和patience从而提高预测准确性。

**Comment by Whimmey** [comment]
> 感谢你的提问，enlarge并没有特殊含义。只是为了方便增大epochs和patience从而提高预测准确性。
也就是说这里enlarge=10恰好和K值相等是一个巧合了。 感谢解答，祝顺利
