### ISSUE TITLE
光伏预测

### ISSUE THREAD

**Issue by xianxiaogao** [FateMurphy/CEEMDAN_LSTM#5]
大佬大佬，先膜拜再说。我想问问此代码可否用于光伏预测，例如对光伏功率分解后，对每个分量进行概率预测（类似回归什么的）然后求和，这样可以吗。因为我是小白，代码也看的不是很懂，所以想请教一下。顺便问一下可以分享文章嘛，因为你这个论文太厉害了，我们学校没有版权，个人买太贵了。当然没有也无所谓，主要是膜拜大佬程序。

**Comment by FateMurphy** [comment]
感谢你的来信！
代码可以用于光伏预测，但是需要注意是预测主要是样本内预测（回归）。样本外的效果并不好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FateMurphy/CEEMDAN_LSTM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 晚上8:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FateMurphy/CEEMDAN_LSTM] 光伏预测 (Issue #5)





 
大佬大佬，先膜拜再说。我想问问此代码可否用于光伏预测，例如对光伏功率分解后，对每个分量进行概率预测（类似回归什么的）然后求和，这样可以吗。因为我是小白，代码也看的不是很懂，所以想请教一下。顺便问一下可以分享文章嘛，因为你这个论文太厉害了，我们学校没有版权，个人买太贵了。当然没有也无所谓，主要是膜拜大佬程序。

**Comment by xianxiaogao** [comment]
感谢回复啊，第一时间就上来了。
是样本内预测，我将三年光伏数据分为（一年训练，一年验证，一年测试），之前只是用了一个pso-vmd对光伏做分解，但是最后预测效果一般，而且存在过拟合，就想着学习学习你的程序，再次感谢大佬回信！
