### ISSUE TITLE
seq2seq

### ISSUE THREAD

**Issue by lisq97** [FateMurphy/CEEMDAN_LSTM#6]
大佬好，我目前在做一个反事实推理的实验，比如，已知因素1为工作日，同时已知因素1为工作日时，某公司当天的用电量（采样频率为每小时一次，shape为（24，1）），求因素1为非工作日时，当天的用电量。我想建立一个模型，输入为已知因素1为工作日时，某公司当天的用电量（24，1），输出为因素1为非工作日时，某公司当天的用电量（24，1）。目前用于训练的数据分为三部分，第一部分，某公司的一年的工作日状态（365，1）；第二部分，此公司的一年实际用电量（365，24，1），作为x；第三部分，预期的此公司的一年非工作日状态用电量（365，24，1），作为y。这样一来我的数据不是传统的时间序列预测问题，更像是seq2seq，想问一下CEEMDAN_LSTM可不可以实现这样的模型？

**Comment by FateMurphy** [comment]
神经网络应该不太适合你描述的反事实推理的实验，强行预测只会显得没有什么根据，但如果逻辑关系（建模公式）能构筑好也可以一试。
