### ISSUE TITLE
关于co-imf2预测的问题

### ISSUE THREAD

**Issue by fxvvv** [FateMurphy/CEEMDAN_LSTM#7]
![02eef4469d1d8ddee90e97e0b8c7259](https://user-images.githubusercontent.com/74700748/231398133-e34a3bac-8158-4658-a0d1-3ff828b61ecf.png)
![5a6d6b3dd5775f9d0771af6be35f433](https://user-images.githubusercontent.com/74700748/231398183-7c0e3213-971b-4f06-a581-e523e6950ce7.png)
大佬好，我用您的代码跑出来的结果co-imf2预测值和真实值之间一直存在一个gap，其他co-imf预测结果都拟合很好，最后预测的R方是负数，可以请教解决方法吗

**Comment by FateMurphy** [comment]
感谢你的提问！预设中的epoch仅为100，可以尝试在参数设置时候提高epoch。如果效果还不好，可以对co-imf2单独使用其他方法预测。

**Comment by kakaka670** [comment]
请问这个问题解决了吗，请教一下
